            - nombre: Caché
  usos: acciones/cache@v4.2.3
  con:
    # Una lista de archivos, directorios y patrones comodín para almacenar en caché y restaurar
    camino:
    # Una clave explícita para restaurar y guardar el caché
    llave:
    # Una cadena multilínea ordenada que enumera las claves con prefijo coincidente, que se utilizan para restaurar la caché obsoleta si no se produce un acierto de caché para la clave. Nota: `cache-hit` devuelve falso en este caso.
    restaurar-claves: # opcional
    # El tamaño del fragmento utilizado para dividir archivos grandes durante la carga, en bytes
    tamaño del fragmento de carga: # opcional
    # Un valor booleano opcional, cuando está habilitado, permite que los ejecutores de Windows guarden o restauren cachés que se pueden restaurar o guardar respectivamente en otras plataformas
    enableCrossOsArchive: # opcional, el valor predeterminado es falso
    # Falla el flujo de trabajo si no se encuentra la entrada de caché
    fail-on-cache-miss: # opcional, el valor predeterminado es falso
    # Verifica si existe una entrada de caché para las entradas dadas (clave, claves de restauración) sin descargar el caché
    solo búsqueda: # opcional, el valor predeterminado es falso
    # Ejecute el paso posterior para guardar el caché incluso si falla otro paso anterior
    guardar siempre: # opcional, el valor predeterminado es falso

            - nombre: Cargar un artefacto de compilación
  usos: acciones/upload-artifact@v4.6.2
  con:
    # Nombre del artefacto
    nombre: # opcional, el valor predeterminado es artefacto
    # Un archivo, directorio o patrón comodín que describe qué cargar
    camino:
    # El comportamiento deseado si no se encuentran archivos utilizando la ruta proporcionada.
Opciones disponibles:
  advertir: emite una advertencia pero no hace que falle la acción
  error: Falla la acción con un mensaje de error
  ignorar: no muestra ninguna advertencia o error, la acción no falla

    if-no-files-found: # opcional, el valor predeterminado es advertir
    # Duración después de la cual el artefacto expirará en días. 0 significa usar la retención predeterminada.
Mínimo 1 día. Máximo 90 días, a menos que se modifique desde la página de configuración del repositorio.

    días de retención: # opcional
    El nivel de compresión de Zlib que se aplicará al archivo de artefactos. El valor puede variar de 0 a 9: - 0: Sin compresión - 1: Máxima velocidad - 6: Compresión predeterminada (igual que GNU Gzip) - 9: Máxima compresión. Los niveles más altos ofrecen una mejor compresión, pero tardan más en completarse. Para archivos grandes que no se comprimen fácilmente, se recomienda un valor de 0 para una carga mucho más rápida.

    nivel de compresión: # opcional, el valor predeterminado es 6
    # Si es verdadero, se eliminará un artefacto con el mismo nombre antes de cargar uno nuevo. Si es falso, la acción fallará si ya existe un artefacto con el nombre especificado. No falla si el artefacto no existe.

    sobrescribir: # opcional, el valor predeterminado es falso
    # Si es verdadero, se incluirán los archivos ocultos en el artefacto. Si es falso, se excluirán.

    include-hidden-files: # opcional, el valor predeterminado es falso



            - nombre: Cerrar problemas obsoletos
  usos: acciones/stale@v9.1.0
  con:
    Token para el repositorio. Se puede pasar mediante `{{ secrets.GITHUB_TOKEN }}`.
    repo-token: # opcional, el valor predeterminado es ${{ github.token }}
    # El mensaje que se publicará sobre el problema al etiquetarlo. Si no se proporciona ninguno, no se marcarán los problemas como obsoletos.
    mensaje de problema obsoleto: # opcional
    # El mensaje que se publicará en la solicitud de extracción al etiquetarla. Si no se proporciona ninguno, no se marcarán las solicitudes de extracción como obsoletas.
    mensaje-previo-obsoleto: # opcional
    # El mensaje que se publicará en el problema al cerrarlo. Si no se proporciona ninguno, no se comentará al cerrar un problema.
    mensaje de cierre de problema: # opcional
    # El mensaje que se publicará en la solicitud de extracción al cerrarla. Si no se proporciona ninguno, no se comentará al cerrar una solicitud de extracción.
    cerrar-pr-mensaje: # opcional
    # El número de días que puede tener una incidencia o solicitud de extracción antes de que se marque como obsoleta. Establézcalo en -1 para que nunca se marquen incidencias ni solicitudes de extracción como obsoletas automáticamente.
    días antes de que se vuelva obsoleto: # opcional, el valor predeterminado es 60
    # El número de días que puede tener un problema antes de que se marque como obsoleto. Configure en -1 para que nunca se marquen los problemas como obsoletos automáticamente. Anule la opción "días antes de que se marque como obsoleto" solo para los problemas.
    días antes de la emisión obsoletos: # opcional
    # El número de días que una solicitud de extracción puede tener antes de que se marque como obsoleta. Se establece en -1 para que nunca se marquen las solicitudes de extracción como obsoletas automáticamente. Anula la opción "días antes de que se marquen obsoletas" solo con las solicitudes de extracción.
    días-antes-de-que-quede-obsoleto: # opcional
    El número de días que se debe esperar para cerrar una incidencia o solicitud de extracción después de que se marque como obsoleta. Establézcalo en -1 para no cerrar nunca incidencias ni solicitudes de extracción obsoletas.
    días-antes-del-cierre: # opcional, el valor predeterminado es 7
    El número de días que se debe esperar para cerrar un problema después de que se marque como obsoleto. Se establece en -1 para no cerrar nunca los problemas obsoletos. Anula la opción "días antes del cierre" solo para los problemas.
    días antes del cierre de la emisión: # opcional
    # El número de días que se debe esperar para cerrar una solicitud de extracción después de que se marque como obsoleta. Se establece en -1 para no cerrar nunca las solicitudes de extracción obsoletas. Se anula la opción "días antes del cierre" solo para las solicitudes de extracción.
    días antes del cierre: # opcional
    # La etiqueta que se aplicará cuando un problema esté obsoleto.
    stale-issue-label: # opcional, el valor predeterminado es obsoleto
    # La etiqueta que se aplicará cuando se cierre un problema.
    cerrar-etiqueta-de-problema: # opcional
    # Las etiquetas que indican que un problema no se marca como obsoleto. Separe las etiquetas con comas (p. ej., "etiqueta1,etiqueta2").
    etiquetas-de-emisión-exentas: # opcional, el valor predeterminado es
    # El motivo a utilizar al cerrar un problema.
    close-issue-reason: # opcional, el valor predeterminado es not_planned
    # La etiqueta que se aplicará cuando una solicitud de extracción esté obsoleta.
    stale-pr-label: # opcional, el valor predeterminado es obsoleto
    # La etiqueta que se aplicará cuando se cierre una solicitud de extracción.
    close-pr-label: # opcional
    # Las etiquetas que indican que una solicitud de extracción está exenta de marcarse como obsoleta. Separe las etiquetas con comas (p. ej., "etiqueta1,etiqueta2").
    except-pr-labels: # opcional, el valor predeterminado es
    Los hitos que indican que una incidencia o una solicitud de incorporación de cambios no se marcan como obsoletos. Separe los hitos con comas (p. ej., "hito1,hito2").
    exentos-hitos: # opcional, el valor predeterminado es
    # Los hitos que eximen a un problema de marcarse como obsoleto. Separe los hitos con comas (p. ej., "hito1,hito2"). Anule la opción "hitos exentos" solo para los problemas.
    indicadores de emisión exentos: # opcional, el valor predeterminado es
    # Los hitos que eximen a una solicitud de incorporación de cambios de ser marcada como obsoleta. Separe los hitos con comas (p. ej., "hito1,hito2"). Anule la opción "exempt-milestones" solo para las solicitudes de incorporación de cambios.
    except-pr-milestones: # opcional, el valor predeterminado es
    # Exime a todos los problemas y solicitudes de extracción con hitos de marcarse como obsoletos. El valor predeterminado es "falso".
    except-all-milestones: # opcional, el valor predeterminado es falso
    # Excluir todos los problemas con hitos de la lista de obsoletos. Anular la opción "excluir todos los hitos" solo para los problemas.
    except-all-issue-milestones: # opcional, el valor predeterminado es
    # Eximir a todas las solicitudes de extracción con hitos de marcarse como obsoletas. Anular la opción "exempt-all-milestones" solo para las solicitudes de extracción.
    except-all-pr-milestones: # opcional, el valor predeterminado es
    # Solo se verifican los problemas o solicitudes de extracción con todas estas etiquetas si están obsoletos. El valor predeterminado es `` (deshabilitado) y puede ser una lista de etiquetas separadas por comas.
    only-labels: # opcional, el valor predeterminado es
    # Solo se verifican los problemas o solicitudes de extracción con al menos una de estas etiquetas si están obsoletos. El valor predeterminado es `` (deshabilitado) y puede ser una lista de etiquetas separadas por comas.
    any-of-labels: # opcional, el valor predeterminado es
    # Solo se verifican los problemas con al menos una de estas etiquetas si están obsoletos. El valor predeterminado es `` (deshabilitado) y puede ser una lista de etiquetas separadas por comas. Anule la opción "cualquiera de las etiquetas" solo para los problemas.
    any-of-issue-labels: # opcional, el valor predeterminado es
    # Solo se verifican las solicitudes de extracción con al menos una de estas etiquetas si están obsoletas. El valor predeterminado es `` (deshabilitado) y puede ser una lista de etiquetas separadas por comas. Anule la opción "cualquiera de las etiquetas" solo para las solicitudes de extracción.
    any-of-pr-labels: # opcional, el valor predeterminado es
    # Solo se verifican los problemas con todas estas etiquetas si están obsoletos. El valor predeterminado es `[]` (deshabilitado) y puede ser una lista de etiquetas separadas por comas. Anule la opción "solo etiquetas" solo para los problemas.
    only-issue-labels: # opcional, el valor predeterminado es
    # Solo se verifican las solicitudes de extracción con todas estas etiquetas si están obsoletas. El valor predeterminado es `[]` (deshabilitado) y puede ser una lista de etiquetas separadas por comas. Anule la opción "only-labels" solo para las solicitudes de extracción.
    only-pr-labels: # opcional, el valor predeterminado es
    # El número máximo de operaciones por ejecución, utilizado para controlar la limitación de velocidad (CRUD de API de GitHub relacionado).
    operaciones-por-ejecución: # opcional, el valor predeterminado es 30
    # Eliminar etiquetas obsoletas de problemas y solicitudes de extracción cuando se actualizan o se comentan.
    remove-stale-when-updated: # opcional, el valor predeterminado es verdadero
    # Eliminar las etiquetas obsoletas de los problemas al actualizarlos o comentarlos. Anular la opción "eliminar obsoleto al actualizar" solo para los problemas.
    remove-issue-stale-when-updated: # opcional, el valor predeterminado es
    # Eliminar las etiquetas obsoletas de las solicitudes de extracción cuando se actualicen o se comenten. Anular la opción "eliminar-obsoletas-al-actualizar" solo con respecto a las solicitudes de extracción.
    remove-pr-stale-when-updated: # opcional, el valor predeterminado es
    # Ejecute el procesador en modo de depuración sin realizar ninguna operación en problemas en vivo.
    solo depuración: # opcional, el valor predeterminado es falso
    # El orden para obtener problemas o solicitudes de extracción. El valor predeterminado es "falso" (en orden descendente).
    ascendente: # opcional, el valor predeterminado es falso
    # Eliminar la rama git después de cerrar una solicitud de extracción obsoleta.
    delete-branch: # opcional, el valor predeterminado es falso
    # La fecha utilizada para omitir la acción obsoleta en el problema o solicitud de extracción creada antes de ella (ISO 8601 o RFC 2822).
    fecha de inicio: # opcional, el valor predeterminado es
    # Los usuarios asignados que eximen una incidencia o solicitud de extracción de marcarse como obsoleta. Separe los usuarios asignados con comas (p. ej., "usuario1,usuario2").
    cesionarios exentos: # opcional, el valor predeterminado es
    # Los asignados que eximen un problema de marcarse como obsoleto. Separe los asignados con comas (p. ej., "usuario1,usuario2"). Anule la opción "eximir-asignados" solo para los problemas.
    exentos-emisión-asignados: # opcional, el valor predeterminado es
    # Los usuarios asignados que eximen una solicitud de extracción de ser marcada como obsoleta. Separe los usuarios asignados con comas (p. ej., "usuario1,usuario2"). Anule la opción "eximir-asignados" solo para las solicitudes de extracción.
    eximir-pr-asignados: # opcional, el valor predeterminado es
    # Exime a todos los problemas y solicitudes de extracción con asignaciones de marcarse como obsoletos. El valor predeterminado es "falso".
    eximir a todos los asignados: # opcional, el valor predeterminado es falso
    # Eximir a todos los problemas con asignatarios de marcarse como obsoletos. Anular la opción "eximir a todos los asignados" solo para los problemas.
    eximir a todos los asignados: # opcional, el valor predeterminado es
    # Eximir a todas las solicitudes de extracción con asignaciones de ser marcadas como obsoletas. Anular la opción "exempt-all-assignes" solo para las solicitudes de extracción.
    eximir a todos los asignatarios de pr: # opcional, el valor predeterminado es
    # Exime a los borradores de solicitudes de extracción de marcarse como obsoletos. El valor predeterminado es falso.
    eximir-borrador-pr: # opcional, el valor predeterminado es falso
    # Mostrar algunas estadísticas al final sobre el flujo de trabajo obsoleto (solo cuando los registros están habilitados).
    enable-statistics: # opcional, el valor predeterminado es verdadero
    # Una lista delimitada por comas de etiquetas para agregar cuando un problema o una solicitud de extracción deja de estar obsoleto.
    etiquetas-para-agregar-cuando-no-estén-obsoletas: # opcional, el valor predeterminado es
    # Una lista delimitada por comas de etiquetas para eliminar cuando un problema o una solicitud de extracción se vuelve obsoleto.
    etiquetas-para-eliminar-cuando-estén-obsoletas: # opcional, el valor predeterminado es
    # Una lista delimitada por comas de etiquetas para eliminar cuando un problema o una solicitud de extracción deja de estar obsoleto.
    etiquetas-para-eliminar-cuando-estén-obsoletas: # opcional, el valor predeterminado es
    # Cualquier actualización (actualización/comentario) puede restablecer el tiempo de inactividad obsoleto en los problemas y solicitudes de extracción.
    ignore-updates: # opcional, el valor predeterminado es falso
    Cualquier actualización (actualización/comentario) puede restablecer el tiempo de inactividad de los problemas. Anule la opción "ignorar actualizaciones" solo para los problemas.
    ignore-issue-updates: # opcional, el valor predeterminado es
    Cualquier actualización (actualización/comentario) puede restablecer el tiempo de inactividad de las solicitudes de extracción. Anule la opción "ignorar actualizaciones" solo para las solicitudes de extracción.
    ignore-pr-updates: # opcional, el valor predeterminado es
    # Sólo los problemas o solicitudes de extracción con un cesionario se marcarán como obsoletos automáticamente.
    include-only-assigned: # opcional, el valor predeterminado es falso


            - nombre: Configurar Java JDK
  usos: acciones/setup-java@v4.7.0
  con:
    La versión de Java que se configurará. Admite una versión completa o parcial de Java. Consulte ejemplos de sintaxis compatibles en el archivo README.
    java-version: # opcional
    # La ruta al archivo `.java-version`. Consulte ejemplos de sintaxis compatibles en el archivo README.
    archivo-versión-java: # opcional
    Distribución de Java. Consulte la lista de distribuciones compatibles en el archivo README.
    distribución:
    # El tipo de paquete (jdk, jre, jdk+fx, jre+fx)
    java-package: # opcional, el valor predeterminado es jdk
    # La arquitectura del paquete (por defecto la arquitectura del ejecutor de acciones)
    arquitectura: # opcional
    # Ruta donde se encuentra el JDK comprimido
    jdkFile: # opcional
    # Configure esta opción si desea que la acción busque la última versión disponible que cumpla con la especificación de la versión.
    check-latest: # opcional
    # ID del repositorio de administración de distribución en el archivo pom.xml. El valor predeterminado es `github`.
    server-id: # opcional, el valor predeterminado es github
    # Nombre de la variable de entorno para el nombre de usuario para la autenticación en el repositorio Apache Maven. El valor predeterminado es $GITHUB_ACTOR
    nombre-de-usuario-servidor: # opcional, el valor predeterminado es GITHUB_ACTOR
    # Nombre de la variable de entorno para la contraseña o token de autenticación en el repositorio Apache Maven. El valor predeterminado es $GITHUB_TOKEN
    contraseña del servidor: # opcional, el valor predeterminado es GITHUB_TOKEN
    Ruta donde se escribirá el archivo settings.xml. El valor predeterminado es ~/.m2.
    ruta de configuración: # opcional
    # Sobrescribir el archivo settings.xml si existe. El valor predeterminado es "true".
    overwrite-settings: # opcional, el valor predeterminado es verdadero
    Clave privada GPG para importar. El valor predeterminado es una cadena vacía.
    clave privada gpg: # opcional
    Nombre de la variable de entorno para la contraseña de la clave privada GPG. El valor predeterminado es $GPG_PASSPHRASE.
    frase de contraseña gpg: # opcional
    # Nombre de la plataforma de compilación donde se almacenarán las dependencias en caché. Puede ser "maven", "gradle" o "sbt".
    caché: # opcional
    # La ruta a un archivo de dependencia: pom.xml, build.gradle, build.sbt, etc. Esta opción se puede usar con la opción `cache`. Si se omite, la acción busca el archivo de dependencia en todo el repositorio. Esta opción admite comodines y una lista de nombres de archivo para almacenar en caché varias dependencias.
    ruta de dependencia de caché: # opcional
    Solución alternativa para pasar el estado del trabajo al paso posterior al trabajo. Esta variable no está diseñada para configuración manual.
    job-status: # opcional, el valor predeterminado es ${{ job.status }}
    # El token utilizado para la autenticación al obtener manifiestos de versiones alojados en github.com, como en el caso de Microsoft Build de OpenJDK. Al ejecutar esta acción en github.com, el valor predeterminado es suficiente. Al ejecutar en GHES, puede pasar un token de acceso personal para github.com si experimenta limitaciones de velocidad.
    token: # opcional, el valor predeterminado es ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Nombre del ID de la cadena de herramientas de Maven si no se desea el nombre predeterminado "${distribution}_${java-version}". Consulte ejemplos de sintaxis compatibles en el archivo de uso avanzado.
    mvn-toolchain-id: # opcional
    # Nombre del proveedor de la cadena de herramientas Maven si no se desea el nombre predeterminado "${distribution}". Consulte ejemplos de sintaxis compatibles en el archivo de uso avanzado.
    mvn-toolchain-vendor: # opcional
          
